name: build-and-deploy-lambda-layers
run-name: ${{ github.actor }} is deploying lambda layers
on: 
  workflow_dispatch:
    inputs:
      ENV_NAME:
        type: choice
        description: Select Environment
        options:
        - dev
        - prod
      BRANCH:
        description: target branch
        default: develop
        required: true
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    name: Build and deploy lambda layers with site packages to dev layers
    if: ${{ github.event.inputs.ENV_NAME  == 'dev' }}
    steps:
      - name: Create src folder
        run: |
          mkdir src
          cd src

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip freeze
          echo "py3_dev_layer_deployment /path/to/src/ ${{github.event.inputs.BRANCH}}"

      - name: ls folder
        run: ls

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    name: Build and deploy lambda layers with site packages to dev layers
    if: ${{ github.event.inputs.ENV_NAME  == 'prod' }}
    steps:
      - run: echo "py3_prod_layer_deployment /path/to/src/ ${{github.event.inputs.BRANCH}}"